[book]
authors = ["Luca Palmieri"]
language = "en"
multilingual = false
src = "src"
title = "100 Exercises To Learn Rust"

# Preprocessors disabled for Cloudflare Pages deployment
# [preprocessor.exercise-linker]
# exercise_root_url = "https://github.com/tangivis/100-exercises-to-learn-rust/tree/main/exercises"


[output.html]
git-repository-url = "https://github.com/tangivis/100-exercises-to-learn-rust"

[output.html.playground]
runnable = false